### ISSUE TITLE
Crash on Lineageos 14.1

### ISSUE THREAD

**Issue by dazzzl** [siacs/VoiceRecorder#15] opened 2017-05-17 15:10 UTC
After recording, the plugin is crashing ...
```
05-17 16:48:10.795 E/MPEG4Writer(  267): The number of recorded samples is 0
05-17 16:48:10.795 W/MPEG4Writer(  267): 0-duration samples found: 1
05-17 16:48:10.795 W/MPEG4Writer(  267): 0-duration samples found: 1
05-17 16:48:10.795 I/MPEG4Writer(  267): Received total/0-length (1/0) buffers and encoded 0 frames. - Audio
05-17 16:48:10.795 I/MPEG4Writer(  267): Audio track drift time: 0 us
05-17 16:48:10.809 E/QC_AACENC(  267): component_deinit:COMPONENT DEINIT...
05-17 16:48:10.809 E/QC_AACENC(  267): AAC Object getting destroyed comp-deinit=1
05-17 16:48:10.809 E/QC_AACENC(  267): OMX AAC component destroyed
05-17 16:48:10.811 I/MediaCodecSource(  267): encoder (audio) stopped
05-17 16:48:10.814 D/audio_hw_primary(  259): in_standby: enter: stream (0xb614fa80) usecase(7: audio-record)
05-17 16:48:10.843 D/audio_hw_primary(  259): in_set_parameters: enter: kvpairs=routing=0
05-17 16:48:10.846 D/MPEG4Writer(  267): Audio track source stopped
05-17 16:48:10.846 D/MPEG4Writer(  267): Audio track stopped
05-17 16:48:10.846 D/MPEG4Writer(  267): Stopping writer thread
05-17 16:48:10.847 D/MPEG4Writer(  267): 0 chunks are written in the last batch
05-17 16:48:10.847 D/MPEG4Writer(  267): Writer thread stopped
05-17 16:48:10.847 D/MPEG4Writer(  267): Audio track stopping
05-17 16:48:10.851 E/MediaRecorder( 6114): stop failed: -1007
05-17 16:48:10.852 D/AndroidRuntime( 6114): Shutting down VM
05-17 16:48:10.858 E/AndroidRuntime( 6114): FATAL EXCEPTION: main
05-17 16:48:10.858 E/AndroidRuntime( 6114): Process: eu.siacs.conversations.voicerecorder, PID: 6114
05-17 16:48:10.858 E/AndroidRuntime( 6114): java.lang.RuntimeException: stop failed.
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at android.media.MediaRecorder.stop(Native Method)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at eu.siacs.conversations.voicerecorder.ui.RecordingActivity.stopRecording(RecordingActivity.java:111)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at eu.siacs.conversations.voicerecorder.ui.RecordingActivity.onClick(RecordingActivity.java:155)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at android.view.View.performClick(View.java:5637)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at android.view.View$PerformClick.run(View.java:22433)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at android.os.Handler.handleCallback(Handler.java:751)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at android.os.Handler.dispatchMessage(Handler.java:95)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at android.os.Looper.loop(Looper.java:154)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at android.app.ActivityThread.main(ActivityThread.java:6128)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at java.lang.reflect.Method.invoke(Native Method)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
05-17 16:48:10.858 E/AndroidRuntime( 6114):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
05-17 16:48:10.866 W/ActivityManager(  553):   Force finishing activity eu.siacs.conversations.voicerecorder/.ui.RecordingActivity
05-17 16:48:10.906 W/ActivityManager(  553):   Force finishing activity eu.siacs.conversations/.ui.ConversationActivity
05-17 16:48:10.973 W/InputMethodManagerService(  553): Focus gain on non-focused client com.android.internal.view.IInputMethodClient$Stub$Proxy@8d25138 (uid=10080 pid=2916)
```

**Comment by killathe** [comment] 2017-05-29 18:57
I also can't use voicerecorder. When cancel or share is pressed, the plugin crashes.
OS: Lineage 14.1 / Android 7.1.2

**Comment by jmankiewicz** [comment] 2017-08-10 12:38
It seems that the generate files in the Voice Recorder folder always have a size of 3227 bytes and the same hash-value, so we are not recording. Do we miss a library or some other dependency? There is also a warning in in the logs about the classloader referencing a missing directory /data/app/eu.siacs..../lib/arm, but no idea if this is significant.

**Comment by zuglufttier** [comment] 2017-10-10 10:38
The error persists with more up to date versions of LineageOS. Has anybody an idea how to debug this or get more information about the error?

**Comment by mheistermann** [comment] 2017-10-10 13:38
On my device (Oneplus2 with recent Lineage 14.1 nightly), there seems to be an issue with codec selection, earlier in the log, at the start of the recoding as opposed to the end:

```
10-10 15:33:04.160  2061 17733 I MediaCodecSource: MediaCodecSource (audio) starting
10-10 15:33:04.161  2061 17738 E QC_AACENC: ioctl AUDIO_SET_AAC_CONFIG failed, 				errno[22]
10-10 15:33:04.162  2061 17738 E QC_AACENC: ioctl AUDIO_START failed, errno[22]
10-10 15:33:04.162  2061 17736 E ACodec  : [OMX.qcom.audio.encoder.aac] ERROR(0x8000100a)
10-10 15:33:04.162  2061 17736 E ACodec  : signalError(omxError 0x8000100a, internalError -2147483648)
10-10 15:33:04.162  2061 17736 E MediaCodec: Codec reported err 0x8000100a, actionCode 0, while in state 6
10-10 15:33:04.164  2053 17735 D audio_hw_primary: in_set_parameters: enter: kvpairs=input_source=1;routing=-2147483644
10-10 15:33:04.165  2061 17733 I MediaCodecSource: MediaCodecSource (audio) started
10-10 15:33:04.165  2061 17733 E MediaCodecSource: Encoder (audio) reported error : 0x8000100a
10-10 15:33:04.166  2053 17735 D audio_hw_primary: start_input_stream: enter: stream(0xf3850740)usecase(16: audio-record)
10-10 15:33:04.166  2061 17743 E MPEG4Writer: The number of recorded samples is 0
[...]

10-10 15:33:04.168 17717 17717 D Voice Recorder: started recording to /storage/emulated/0/Voice Recorder/RECORDING_20171010_153304129.m4a

```
I suppose AAC is not available; I would expect the android API to return an error somewhere, but it appears neither MediaRecorder.prepare() nor .start() raise an exception, as evidenced by that "started recording" log line.
This assumes the play store version is the same as current master.

**Comment by zuglufttier** [comment] 2017-10-10 14:04
@luk1337 found out that changing the codec to AAC seems to do the trick: https://gist.github.com/luk1337/0760faaa37dadbbc8ed371cf374be682

**Comment by librejoker** [comment] 2017-10-25 02:16
Thanks zuglufttier. Now voice recording does actually work again.

**Comment by zuglufttier** [comment] 2017-10-25 13:46
Don't thank me! Thank the developers ;)

So this is fixed in recent nightlies, issue can be closed.

**Comment by zuglufttier** [comment] 2017-10-25 15:08
Oh, sorry, I was wrong here... I mixed things a bit up ;) On LineageOS you don't need this plugin anymore because now you can use the default recorder app that comes with LOS and that was fixed in the last nightlies.

**Comment by librejoker** [comment] 2017-10-25 15:14
I had this problem on RR and SlimRoms. On RR, which is based on LOS, there is a recorder app who can be used, but audio files get much bigger than with this app. I don't consider it an appropriate alternative, but maybe LOS recorder is different.

**Comment by jkrenzer** [comment] 2017-10-26 14:25
@librejoker 
I use LOS and the same here. The recorder does not have an overlay-function like the plugin and you have to separately record and then go through the share-menu to get the message out. It's certainly a workaround for the time being but the plugin is much easier and faster to exchange voice messages.

**Comment by gudbes** [comment] 2017-11-06 09:54
Hello, I use LOS 14.1 on my onePlus and i'm in the same situation. How do I get a developer to update this code because I use this plugin every day and it's really annoying:)

Thank you in advance.

gudbes

**Comment by iNPUTmice** [comment] 2017-11-06 09:59
Someone should report this to LineageOS.

**Comment by gudbes** [comment] 2017-11-06 10:16
Thank you for your answer, I'll see how I can explain my problem to them.
Anyway bravo for your work on "conversations", I'm a fan of it:)

**Comment by gudbes** [comment] 2017-11-06 16:12
I need to compile the application with the patch of the following link:[]( https://gist.github.com/luk1337/0760faaa37dadbbc8ed371cf374be682)
but I don't know how to do it I looked on the Internet but I can't find a tutorial to explain how to do it. With you a link to a site to have a little more explanation

**Comment by librejoker** [comment] 2017-11-06 17:52
@gudbes
You need to install Android Studio [1] and choose "Check out project from version control" -> Git. copy-paste [2]. You will also need to install SDK 22 and SDK build tools 22.0.1 . Don't forget to tick "Show Package Details" to see older build tools.
Then you can edit the code and finally build. Build -> Build APK.

[1] https://developer.android.com/studio/index.html
[2] https://github.com/siacs/VoiceRecorder.git

I could also also provide a download link to my compiled APK, but of course installing from unknown sources is not recommended. If you want to take the risk let me know.

**Comment by gudbes** [comment] 2017-11-07 07:44
@librejoker thank you for the explication. I'll try it myself for curiosity and if I can't do it, I'll tell you again:)

thanks again

**Comment by gudbes** [comment] 2017-11-07 13:10
@librejoker , I installed android studio (SDK+DSK tools) but i have a question. With the file of luk1337, i must remplace the old code by 👍 
mRecorder = new MediaRecorder();
```
 		mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
 		mRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
-		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.JELLY_BEAN) {
-			mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.HE_AAC);
-			mRecorder.setAudioEncodingBitRate(48000);
-		} else {
-			mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
-			mRecorder.setAudioEncodingBitRate(64000);
-		}
+		mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
+		mRecorder.setAudioEncodingBitRate(64000);
 		mRecorder.setAudioSamplingRate(16000);
 		mOutputFile = getOutputFile();
mOutputFile.getParentFile().mkdirs();
```

or the file is an executable ?

thank you

gudbes

**Comment by gudbes** [comment] 2017-11-08 17:07
I'm posting the link of APK application patched for use on Android 7 (tested on version 7.1).
Important: Please read the "READ_ME" file contained in this link.

https://drive.google.com/drive/folders/1WS_D3uBSon3hDrXfdtvp7gdrpg6lxeDj?usp=sharing

gudbes

**Comment by librejoker** [comment] 2017-11-08 17:56
So you did come up with the solution yourself? Great. Is it working? I found playing messages inline isn't, but I really don't care. It's just great to have it working at all.
Just read your readme file. Maybe you should provide a md5/sha256 checksum so people can verify your file wasn't altered by anyone else.

**Comment by iNPUTmice** [comment] 2017-11-08 18:01
In case this isn't clear. The Voice Recorder is working on Android 8 (stock) and Android 7.1 (some outdated version of LineageOS running on my Nexus 4). So this is either a platform specific bug or a regression in newer versions of LineageOS. You should report this to LineageOS.

**Comment by gudbes** [comment] 2017-11-08 19:15
@librejoker: yes the app works under lineage Bones for me anyway but I wait for the returns if necessary. On your advice, I'll try to add the checksum.

iNPUTmice : Sorry, I didn't think the bug was related to lineage only. I went to the lineage site to explain the bug but I didn't quite understand the procedure so I went to the IRC channel where I asked for help by indicating the link of the post to see if the debug logs requested were those of the first post but I didn't get an answer. I was just told that to solve the problem of compiling the application with the Luk1334 patch and thanks to @jo, I decided to launch myself and propose a patch for the next ones. I know that my solution is not clean and I explain it clearly in my readme.

By hoping that my sharing is beneficial to others and not the other way around. My thoughts are good and I want to share.

**Comment by Failure404** [comment] 2017-12-13 17:45
@gudbes Thank you very much for doing this. I now have a 100% working plugin and don't have to wait for eternity that some reluctant dev will fix this.

**Comment by gudbes** [comment] 2017-12-13 20:37
@Failure404
With pleasure 🙂

**Comment by decripter37** [comment] 2018-05-07 19:02
After the last update of Conversation the fix doesn't work anynore.

**Comment by zuglufttier** [comment] 2018-05-08 06:59
The voice recorder is now integrated into Conversations: https://github.com/siacs/Conversations/releases/tag/2.2.0
Please update and remove the old plugin!

**Comment by iNPUTmice** [comment] 2018-05-08 07:37
Closing in favor of https://github.com/siacs/Conversations/issues/3021

**Closed by iNPUTmice** 2018-05-08 07:37 UTC
